// <auto-generated />
namespace LanParty.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Moved_Property_From_Booking_To_Seat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Moved_Property_From_Booking_To_Seat));
        
        string IMigrationMetadata.Id
        {
            get { return "201706202249184_Moved_Property_From_Booking_To_Seat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
